version: 0.2

env:
  shell: bash
phases:
  pre_build:
    commands:
      - aws --version || true
      - npm version
  build:
    commands:
      - cd frontend
      - echo "REACT_APP_API=https://thingler.io" > .env.production.local
      - PRICE_LEVELS=$(curl -s -X GET "https://api.thingler.io/day-ahead?levels")
      - FILE_PATH="src/components/EnergyPriceLevels.js"
      - sed -i "/const basePriceLevels = {/,/};/c const basePriceLevels = ${PRICE_LEVELS};" "$FILE_PATH"
      - npm install
      - ./deploy.sh
